Repository br-cz/neighbourhood, pull requests merged in 2024-03, with the labels that each got.

#80 NEIG-17: Profile Card Frontend
  __test__/editAccountDetails.test.tsx
  app/profile/page.tsx
  components/ProfileCard/AccountSettingsModal.tsx
  components/ProfileCard/ProfileCard.module.css
  components/ProfileCard/ProfileCard.tsx
Labels: enhancement

#93 NEIG-142 & NEIG-25: People Search & Sort
  app/people/page.tsx
  components/UserList/UserList.tsx
  utils/sortUtils.ts
Labels: do not merge

#95 NEIG-141 & 160: Marketplace Sort & Schema Update
  amplify/backend/api/neighbourhood/schema.graphql
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  app/marketplace/page.tsx
  components/Marketplace/MarketplaceFeed.tsx
  components/Marketplace/marketplaceSort.ts
  components/ProfileCard/ProfileCard.tsx
  src/API.ts
  src/api/services/user.tsx
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/models/index.d.ts
  src/models/schema.d.ts
  src/models/schema.js
  utils/timeUtils.ts
Labels: enhancement

#87 NEIG-26: User Profile Previews
  components/UserListItem/UserListItem.module.css
  components/UserListItem/UserListItem.tsx
  components/UserListItem/UserListItemPreview.tsx
  src/api/services/community.tsx
  src/api/services/friend.tsx
  types/types.ts
Labels: enhancement

#120 NEIG-171: Remove age/add relevantCommunities to schema
  amplify/backend/api/neighbourhood/schema.graphql
  src/API.ts
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/models/index.d.ts
  src/models/schema.js
Labels: schema change

#124 NEIG-170: S3 Image Expiration Fix
  components/CommentCard/CommentCard.tsx
  components/CommunityButton/CommunityButton.tsx
  components/CommunityListItem/CommunityListItem.tsx
  components/EventCard/EventCard.tsx
  components/Marketplace/MarketplaceCard.tsx
  components/Marketplace/ViewListingModal.tsx
  components/PostCard/PostCard.tsx
  components/ProfileCard/CustomizeProfileModal.tsx
  components/ProfileCard/ProfileCard.tsx
  components/UserButton/UserButton.tsx
  components/UserListItem/UserListItem.tsx
  components/UserListItem/UserListItemPreview.tsx
  components/ViewEventModal/ViewEventModal.tsx
  components/utils/s3Helpers/CommunityImageS3Helper.tsx
  components/utils/s3Helpers/EventImageS3Helper.tsx
  components/utils/s3Helpers/ItemForSaleImageS3Helper.tsx
  components/utils/s3Helpers/PostImageS3Helper.tsx
  components/utils/s3Helpers/UserProfilePictureS3Helper.tsx
  components/utils/utilFunctions.tsx
  jest.setup.cjs
Labels: bug

#125 Schema Update
  amplify/backend/api/neighbourhood/schema.graphql
  src/API.ts
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/schema.json
  src/graphql/subscriptions.ts
  src/models/index.d.ts
  src/models/schema.js
Labels: schema change

#127 Hotfix for S3 - Retrieval errors fix and clean up database
  components/EventCard/EventCard.tsx
  components/utils/s3Helpers/CommunityImageS3Helper.tsx
  components/utils/s3Helpers/EventImageS3Helper.tsx
  components/utils/s3Helpers/ItemForSaleImageS3Helper.tsx
  components/utils/s3Helpers/PostImageS3Helper.tsx
Labels: bug

#128 NEIG-172: Retrieve placeholder img for event/marketplace when none available
  components/utils/s3Helpers/EventImageS3Helper.tsx
  components/utils/s3Helpers/ItemForSaleImageS3Helper.tsx
  components/utils/utilFunctions.tsx
Labels: bug
